"""user_schema_model_init

Revision ID: 446cb87d5e05
Revises: 
Create Date: 2026-07-27 20:34:21.946731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import authloom


# revision identifiers, used by Alembic.
revision: str = '446cb87d5e05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authloom_users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', authloom.utils.time.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', authloom.utils.time.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authloom_users_email'), 'authloom_users', ['email'], unique=True)
    op.create_index(op.f('ix_authloom_users_name'), 'authloom_users', ['name'], unique=False)
    op.create_table('authloom_sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('expires_at', authloom.utils.time.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', authloom.utils.time.UTCDateTime(), nullable=True),
    sa.Column('created_at', authloom.utils.time.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['authloom_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authloom_sessions_token_hash'), 'authloom_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_authloom_sessions_user_id'), 'authloom_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authloom_sessions_user_id'), table_name='authloom_sessions')
    op.drop_index(op.f('ix_authloom_sessions_token_hash'), table_name='authloom_sessions')
    op.drop_table('authloom_sessions')
    op.drop_index(op.f('ix_authloom_users_name'), table_name='authloom_users')
    op.drop_index(op.f('ix_authloom_users_email'), table_name='authloom_users')
    op.drop_table('authloom_users')
    # ### end Alembic commands ###
